// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrT1CZWQQxDZHyga2LOH62d6-j4UEXIJ4',
    appId: '1:1091907064831:web:41ffd9017552f1231b4dca',
    messagingSenderId: '1091907064831',
    projectId: 'pit-stop-ee77a',
    authDomain: 'pit-stop-ee77a.firebaseapp.com',
    storageBucket: 'pit-stop-ee77a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hhYUiUdwvK-Z5AHtdbLEsSTZqqARee8',
    appId: '1:1091907064831:android:afa291ae201bee9c1b4dca',
    messagingSenderId: '1091907064831',
    projectId: 'pit-stop-ee77a',
    storageBucket: 'pit-stop-ee77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzpUwqftHivRy48_JRZTGe_awOpk0DdvQ',
    appId: '1:1091907064831:ios:0f80c27b02668d4b1b4dca',
    messagingSenderId: '1091907064831',
    projectId: 'pit-stop-ee77a',
    storageBucket: 'pit-stop-ee77a.firebasestorage.app',
    iosBundleId: 'com.example.androidStudio',
  );

}